#!/usr/bin/env bash

BASEDIR=$(dirname "$0")
source $BASEDIR/../util/bugm_helpers.sh

params() {
  (
    SIMULATION_WEEKS
    MANAGER_OPENING_BALANCE
    HACKER_OPENING_BALANCE
    NUMBER_OF_HACKERS
    TIER1_VOLUME
    TIER1_PRICE
    TIER2_VOLUME
    TIER2_PRICE
    TIER3_VOLUME
    TIER3_PRICE
    TIER4_VOLUME
    TIER4_PRICE
    TIER5_VOLUME
    TIER5_PRICE
    ISSUE_PCT_CRITICAL
  )
}

bot() {
  echo "START `date`"
  ( echo Rebuild System  ; $BASEDIR/rebuild      ) &&
  ( echo Load User Data  ; $BASEDIR/user_load    ) &&
  ( echo Load Trackers   ; $BASEDIR/tracker_load ) &&
  ( echo Trade System    ; $BASEDIR/trade        ) &&
  ( echo Capture Results ; $BASEDIR/capture      ) &&
  echo "DONE `date`"
}

results() {
  echo "Results Under Construction for $TRIAL_NAME"
}

run_bot_and_show_results $@
