#!/usr/bin/env bash

bmx user create --balance=1000 --usermail=user1@bugmark.net
bmx user create --balance=1000 --usermail=user2@bugmark.net
bmx user create --balance=1000 --usermail=user3@bugmark.net

