#!/usr/bin/env bash

echo "----- FORECAST1 TOTAL REBUILD ---------------------"
echo "START `date`"
( echo Clear Old Data ; ./forecast1/clear         ) &&
( echo Load User Data ; ./forecast1/user_load.sh  ) &&
( echo Load Repos     ; ./forecast1/repo_load     ) &&
( echo Load Offers    ; ./forecast1/offer_load    ) &&
( echo Load Contracts ; ./forecast1/contract_load ) &&
( echo Counts         ; ./forecast1/count         ) &&
echo "DONE `date`"
