#!/usr/bin/env ruby
# SPDX-License-Identifier: MPL-2.0

require 'json'

repo_names = %w(Repo1 Repo2 Repo3)

# create repos
repo_hash  = repo_names.reduce({}) do |hash, name|
  hash[name] = JSON.parse(`bmx repo create #{name} --type=Test`)["uuid"]
  hash
end

pp repo_hash

# create issues
repo_hash.each do |repo_name, repo_uuid|
  [1,2].map do |id|
    exid = "#{repo_name}_Issue#{id}"
    cmd = "bmx issue sync #{exid} --title=#{exid} --status=open --repo_uuid=#{repo_uuid}"
    system cmd
  end
end
