#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0

abort() {
  echo "Usage: all <GitHub|Test>"
  exit 1
}

[ "$#" == "0" ] && abort
[ "$1" == "GitHub" ] || [ "$1" == "Test" ] || abort

echo "----- BUGMARK-CLI TOTAL REBUILD TEST ---------------------"
echo "START `date`"
( echo Clear Old Data ; ./rebuild/clear         ) &&
( echo Load User Data ; ./rebuild/user_load     ) &&
( echo Load Test Repo ; ./rebuild/repo_load $1  ) &&
( echo Load Offers    ; ./rebuild/offer_load    ) &&
( echo Load Contracts ; ./rebuild/contract_load ) &&
( echo Counts         ; ./rebuild/count         ) &&
echo "DONE `date`"
