#!/usr/bin/env bash

echo "----- BUGMARK-CLI TOTAL REBUILD ---------------------"
echo "START `date`"

( echo Clear Old Data ; ./rebuild/clear         ) && 
( echo Load User Data ; ./rebuild/user_load     ) &&
( echo Load GH data   ; ./rebuild/gh_load       ) &&
( echo Load OfferBU   ; ./rebuild/offer_bu_load ) &&
( echo Load OfferBF   ; ./rebuild/offer_bf_load ) &&
( echo Load Contracts ; ./rebuild/contract_load ) &&
( echo Counts         ; ./rebuild/count         ) 

echo "DONE `date`"
