#!/usr/bin/env python

from subprocess import check_output
import json
import sys
import datetime

# Advance server time by one day
check_output(["bmx", "host", "increment_day_offset"])
# This should pay out maturing contracts
print(" pay out", end="")
contracts_rtn = check_output(["bmx", "contract", "list"])
contracts_obj = json.loads(contracts_rtn.decode("utf-8"))
for contract in contracts_obj:
    check_output(["bmx", "contract", "resolve", contract["uuid"]])
 
print(" [DONE]")
