#!/usr/bin/env python

import bugm_util as bugm

# create simulation repository

repo_name    = bugm.env('REPO_NAME' , "TrivialCaseRepo")

bugm.run_json(["repo create",
               repo_name,
               "--type=Test"])

