#!/usr/bin/env python

# ----- user_load -----

import bugm_util as bugm

# simulation parameters
num_workers    = bugm.env('NUM_WORKERS'   , 1)
worker_balance = bugm.env('WORKER_BALANCE', 10000)
funder_balance = bugm.env('FUNDER_BALANCE', 100000)

# create users
def create_user(email, balance="0"):
  bugm.run_json(["user create",
                 "--usermail="+email,
                 "--password=bugmark",
                 "--balance="+balance])

# create funder
create_user("test-funder@bugmark.net", str(funder_balance))

# create workers
for w in range(int(num_workers)):
  email = "test-worker"+str(w)+"@bugmark.net"
  create_user(email, str(worker_balance))

